### ISSUE TITLE
Allow a way to create differed timers 

### ISSUE THREAD

**Issue by kivister** [ArpNetworking/metrics-client-java#10]
Currently there is no way to create a differed timer, use case: I need to start measurement of time at this instance however I don't have a name for my timer yet.

**Comment by vjkoskela** [comment]
Correct, there is no construct for a deferred timer. However, you can time the event you are interested in and then use metrics.setTimer(<name>, <value>, <unit>) to explicitly add a sample to the desired timer. This method was designed for use in cases where clients had existing timing code they wished to integrate. However, it also works in your case where you do not know the timer name until you are ready to record the sample.

In the next major revision we plan to formally expose our underlying Timer (nothing complex mind you) so you would be able to use that without having to write your own. If you could provide some more insight into your use case I would like to give it some thought as to what we could include in the next or future revisions to address your use case.

**Comment by vjkoskela** [comment]
The stop watch is being defined here: https://github.com/ArpNetworking/metrics-client-java/pull/40

**Comment by vjkoskela** [comment]
Stop watch in #40 merged and released in 0.8.0
