### ISSUE TITLE
Investigate use of the caching host provider in TsdMetricsFactory

### ISSUE THREAD

**Issue by BrandonArp** [ArpNetworking/metrics-client-java#23]
The TsdMetricsFactory will use a CachingHostResolver to resolve the hostname in the Builder.  The use of a CachingHostResolver is confusing as the hostname is only resolved once and then stored in the _hostname field of the TsdMetricsFactory.

Fix this by using a non-caching resolver or continually looking up the host name from the resolver.

**Comment by vjkoskela** [comment]
This is addressed in #26.
