### ISSUE TITLE
Remove Double Check Map Insertion

### ISSUE THREAD

**Issue by vjkoskela** [ArpNetworking/metrics-client-java#5]
With Java7 we were used a pattern of get() followed by a conditional putIfAbsent() call. Java8 introduces computeIfAbsent() allowing the constructor call to be delegated to the ConcurrentMap. This should enable removal of the double check map insertion. In turn, it should simplify testing. In particular, we can restore 100% coverage with existing tests and remove the multithreadedtc dependency (and any tests using it).

**Comment by BrandonArp** [comment]
Pull requests are better than issues ( :

**Comment by vjkoskela** [comment]
I am planning on including it with the 2F changes.

**Comment by vjkoskela** [comment]
This was fixed in: https://github.com/ArpNetworking/metrics-client-java/pull/9
